<a href="https://colab.research.google.com/github/MariaAkterKhadiza/Phitron_AI-ML_Batch_01/blob/main/Mariya_Dewan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Email address:khadizatulmaria2002@gmail.com**

In [ ]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


# answer to Q1

In [ ]:
ages_arr = np.array(ages)
salaries_arr = np.array(salaries)

print(ages_arr.dtype)
print(ages_arr.ndim)
print( ages_arr.shape)
print( ages_arr.size)

print(salaries_arr.dtype)
print(salaries_arr.ndim)
print(salaries_arr.shape)
print(salaries_arr.size)

int64
1
(10,)
10
int64
1
(10,)
10


# Q2

In [ ]:
print(np.max(salaries_arr))
print(np.min(salaries_arr))
print(np.mean(salaries_arr))

print(np.mean(ages_arr))

89735
30769
57446.9
38.5


# Q3

In [ ]:
greater_than_30 = ages_arr[ages_arr > 30]
print(greater_than_30)

print(greater_than_30.size)

[56 46 32 38 56 36 40]
7


Q4

In [ ]:
print(ages_arr)
new_ages = ages_arr + 5
print(new_ages)

[56 46 32 25 38 56 36 40 28 28]
[61 51 37 30 43 61 41 45 33 33]


#  Q5

In [ ]:
total_salary = np.sum(salaries_arr)
print(total_salary)

#print(np.max(salaries_arr))
#print(np.min(salaries_arr))

diff = np.max(salaries_arr) - np.min(salaries_arr)
print(diff)

574469
58966


# Q6

In [ ]:
df = pd.read_csv("employees.csv")
print(df)
#print(df.head())
print(df.info())
print(df.describe())

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes
None
             id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.00

# Q7

In [ ]:

df = pd.read_csv("employees.csv")
#print(df[["id", "age", "salary"]])

print(df[["id", "age", "salary"]].tail(3))


   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


# Q8

In [ ]:
it_employees = df[df["dept"] == "IT"]
print( it_employees)
print(it_employees.shape[0])


   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
3


# Q9

In [ ]:
top3 = df.sort_values(by="salary", ascending=False).head(3)
print(top3[["dept", "age", "salary"]])


      dept  age  salary
6  Finance   36   89735
7       IT   40   86101
0       HR   56   77191


# Q10

In [ ]:
df.loc[df["salary"] > 80000, "salary"] = 80000

new_avg = df["salary"].mean()

print(new_avg)

55863.3
