<a href="https://colab.research.google.com/github/MariaAkterKhadiza/Phitron_AI-ML_Batch_01/blob/main/REVISION_(10DAYS_OFF).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPAY

In [ ]:
import numpy as np

a = np.array([1, 2, 3]) # 1 + 4 = 5 ai vabe calculate hocce
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [ ]:
arr = [1,2 ,3]
# arra r sathe abr o arra 4 bar print hocce
#print(arr * 5)

arr = [ x*5 for x in arr]
print(arr)

[5, 10, 15]


**ND_ARRAY**

In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5]) #  1D

arr2 = np.array([[1,2,3,], # 2D
                 [4,5,6]])


arr3 = np.array([])

In [ ]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])


# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


# ndarray data type

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)

arr = np.array([1.5, 2.5, 3.5])
print(arr.dtype)


int64
float64


In [ ]:
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)

float64
<U32
<U32


# selecting data type for an array

In [ ]:
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)

arr = arr.astype(np.int32)
print(arr.dtype)

int16
[  1   2 300]
int32


nd array creation from existing data

In [ ]:
lst = [10,20,30,40 , 40.5]
arr = np.array(lst, dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32


In [ ]:
mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

print(arr)
print(type(arr))
print(arr.dtype)

['10' 'True' 'Hello']
<class 'numpy.ndarray'>
<U21


In [ ]:
matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [ ]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [ ]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [ ]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



#
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# creating ndarray from scratch

In [ ]:
import numpy as np

# np.zeros

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])

arr = np.zeros((2,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same

print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [ ]:
import numpy as np

# np.zeros

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2


])

arr = np.zeros((2,3),dtype=np.int8)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

arr = np.zeros_like(arr3) ## arr3 shape same
arr = np.ones_like(arr3)
arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)
